# Generated by Django 4.2.4 on 2023-08-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_module_image'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomImage',
        ),
    ]
