# Generated by Django 4.2.5 on 2023-09-13 04:52

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtailmarkdown.blocks
import wagtailmarkdown.fields


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "chapter",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("icon", wagtail.blocks.CharBlock(default="list-ul")),
                                ("content", wagtailmarkdown.blocks.MarkdownBlock(icon="code")),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
    ]
