# Generated by Django 4.2.5 on 2023-11-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="order",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
