# Generated by Django 4.2.5 on 2023-11-01 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_chapter_order"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("chapter", "order")},
        ),
    ]
