#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python /app/manage.py collectstatic --noinput
# Temporarily turn off 'errexit' for the createsuperuser command
set +o errexit
python manage.py createsuperuser --noinput || echo "Warning: Superuser could not be created. It may already exist."
set -o errexit
python /app/manage.py setup_social_apps

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app --timeout 600 --log-level debug
